version: '3.1'

services:

  db:
    image: postgres
    restart: "no"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/docker/volumes/postgresql/_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: "no"
    ports:
      - "8081:8080"
    volumes:
      - /var/lib/docker/volumes/adminer/_data:/var/lib/adminer/data
